# Generated by Django 2.0.dev20170411164641 on 2017-04-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarest', '0009_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ManyToManyField(to='sarest.Rating'),
        ),
    ]
