# Generated by Django 2.0.dev20170411164641 on 2017-04-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarest', '0010_auto_20170423_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='sarest.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
