# Generated by Django 2.0.dev20170411164641 on 2017-04-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarest', '0011_auto_20170425_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
