# Generated by Django 2.0.dev20170411164641 on 2017-04-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarest', '0015_auto_20170426_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sarest.Category'),
        ),
    ]
