# Generated by Django 2.0.dev20170411164641 on 2017-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarest', '0020_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='flowers',
            new_name='followers',
        ),
    ]
