# Generated by Django 2.0.dev20170411164641 on 2017-04-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarest', '0025_book_publish_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBooks',
            new_name='Reader',
        ),
    ]
